config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :mtasks, :only => [:index, :create, :edit, :update, :destroy] do
  member do
    post 'finish'
    post 'restore'
  end
end

app/models/mtask.rb
class Mtask < ActiveRecord::Base
  unloadable


  belongs_to :author, :class_name => 'User'
  belongs_to :assigned_to, :class_name => 'Principal'
end

app/controllers/mtasks_controller.rb
class MtasksController < ApplicationController
  unloadable


  before_filter :find_project, :authorize
  before_filter :load_and_validate_mtask, only: [:edit, :update, :finish, :restore, :destroy]

  def index
    @mtask = Mtask.new
    @new_tasks = Mtask.where(project_id: @project.id, finished: false).order(due_date: :desc, created_at: :desc)
    @finished_tasks = Mtask.where(project_id: @project.id, finished: true).order(due_date: :desc, created_at: :desc)
  end

  def create
    mtask = Mtask.new(mtask_params)
    mtask.author = find_current_user
    mtask.project_id = @project.id
    mtask.save

    redirect_to mtasks_url(project_id: @project.identifier)
  end

  def edit
  end

  def update
    if @mtask.update(mtask_params)
      redirect_to mtasks_url(project_id: @project.identifier)
    else
      render 'edit'
    end
  end

  def finish
    if @mtask.update(finished: true)
      flash[:notice] = 'Task finished.'
    end

    redirect_to mtasks_url(project_id: @project.identifier)
  end

  def restore
    if @mtask.update(finished: false)
      flash[:notice] = 'Task restored.'
    end

    redirect_to mtasks_url(project_id: @project.identifier)
  end

  def destroy
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def load_and_validate_mtask
    @mtask = Mtask.find(params[:id])

    if @mtask.project_id != @project.id
      redirect_to mtasks_url(project_id: @project.identifier)
    end
  end

  def mtask_params
    params.require(:mtask).permit(:text, :author_id, :assigned_to_id, :due_date)
  end
end

app/helpers/mtasks_helper.rb
module MtasksHelper
end

app/views/mtasks/_form.html.erb
<%= error_messages_for 'mtask' %>

<div class="box tabular">
  <p>
    <label for="text">Task description</label>
    <%= f.text_field :text %>
  </p>

  <p id="due_date_area">
    <label for="due_date">Due date</label>
    <%= f.date_field(:due_date, :size => 10, required: false) %>
    <%= calendar_for('issue_due_date') %>
  </p>
</div>

app/views/mtasks/_mtasks.html.erb
<div class="autoscroll">
  <table class="list issues">
    <thead>
      <caption><%= caption %></caption>
      <tr>
        <th>Due date</th>
        <th>Task</th>
        <th>Author</th>
        <th>Assigned to</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% mtasks.each do |mtask| %>
        <tr id="mtask-<%= mtask.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td><%= mtask.due_date %></td>
          <td><%= mtask.text %></td>
          <td>
            <% if mtask.author.present? %>
              <%= mtask.author.name %>
            <% end %>
          </td>
          <td>
            <% if mtask.assigned_to.present?   %>
              <%= mtask.assigned_to.name %>
            <% end %>
          </td>
          <td>
            <% if mtask.finished %>
              <%= form_for :mtask, url: restore_mtask_path(mtask, project_id: @project.identifier) do |f| %>
                <%= submit_tag 'Restore' %>
              <% end %>
            <% else %>
              <%= form_for :mtask, url: finish_mtask_path(mtask, project_id: @project.identifier) do |f| %>
                <%= submit_tag 'Finish' %>
              <% end %>
            <% end %>
          </td>
      </tr>
      <%end %>
    </tbody>
  </table>
</div>

app/views/mtasks/index.html.erb
<%= form_for @mtask, url: mtasks_path(project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

<%= render partial: 'mtasks', locals: {mtasks: @new_tasks, caption: 'New tasks'} %>
<%= render partial: 'mtasks', locals: {mtasks: @finished_tasks, caption: 'Finished tasks'} %>

app/views/mtasks/update.html.erb
<h2>MtasksController#update</h2>